apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-old
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-old
  template:
    metadata:
      labels:
        app: apache-old
    spec:
      containers:
        - name: apache
          image: httpd:2.4.38
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache-old
spec:
  selector:
    app: apache-old
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
